Removed Option to Over-write Existing File. Modified README/Instructions Accordingly.

diff --git a/pdf-ap b/pdf-ap
--- a/pdf-ap
+++ b/pdf-ap
@@ -12,37 +12,40 @@ check_pkg() {
 check_pkg pdftk
 check_pkg fzf
 
+export PDF_LOC="$HOME/Books"
+export TEMPLATE_LOC="$HOME/Templates"
+
+export FULL_PDF_LOC="$(readlink $PDF_LOC || echo $PDF_LOC)"
+export FULL_TEMPLATE_LOC="$(readlink $TEMPLATE_LOC || echo $TEMPLATE_LOC)"
+
 if [ ! -z "$TERMUX_VERSION" ]; then
-  if [ ! -L "$HOME/Books" ]; then
+  if [ ! -L "$PDF_LOC" ]; then
     echo "ERROR: '~/Books' should be a link to your books location!" >&2
-    echo " TRY running: 'ln -s /sdcard/Books/<BOOK_LOCATION> ~/Books'" >&2
+    echo " TRY running: 'ln -s /sdcard/Books ~/Books'" >&2
     exit 1
   fi
-  if [ ! -L "$HOME/Templates" ]; then
+  if [ ! -L "$TEMPLATE_LOC" ]; then
     echo "ERROR: '~/Templates' should be a link to your templates location!" >&2
-    echo " TRY running: 'ln -s /sdcard/noteTemplates ~/Templates'" >&2
+    echo " TRY running: 'ln -s /sdcard/noteTemplate ~/Templates'" >&2
     exit 1
   fi
-fi
+else
+  if [ ! -L "$PDF_LOC" -o ! -d "$PDF_LOC" ] ;then
+    echo "ERROR: Directory '$PDF_LOC' Does not Exist!" >&2
+    exit 1
+  fi
 
-export PDF_LOC="$HOME/Books/"
-export TEMPLATE_LOC="$HOME/Templates/"
-
-if [ ! -d "$PDF_LOC" ] ;then
-  echo "ERROR: Directory '$PDF_LOC' Does not Exist!" >&2
-  exit 1
-fi
-
-if [ ! -d "$TEMPLATE_LOC" ] ;then
-  echo "ERROR: Directory '$PDF_LOC' Does not Exist!" >&2
-  exit 1
+  if [ ! -L "$TEMPLATE_LOC" -o ! -d "$TEMPLATE_LOC" ] ;then
+    echo "ERROR: Directory '$TEMPLATE_LOC' Does not Exist!" >&2
+    exit 1
+  fi
 fi
 
 read -p 'Hit Enter then Search for the Input PDF: ' foo
-export INPUT_PDF="$PDF_LOC/$(cd $PDF_LOC; fzf -q '.pdf$ ')"
+export INPUT_PDF="$FULL_PDF_LOC/$(cd $FULL_PDF_LOC; fzf -q '.pdf$ ')"
 
 read -p 'Hit Enter then Search for the Template to Add: ' foo
-export TEMPLATE_PDF="$TEMPLATE_LOC/$(cd $TEMPLATE_LOC; fzf -q '.pdf$ ')"
+export TEMPLATE_PDF="$FULL_TEMPLATE_LOC/$(cd $FULL_TEMPLATE_LOC; fzf -q '.pdf$ ')"
 
 read -p 'page number to append template after: ' PAGE; export PAGE
 
@@ -59,44 +62,41 @@ if [ ! -d "$HOME/tmp" ]; then
 fi
 
 if [ -f "$INPUT_PDF" -a -f "$TEMPLATE_PDF" ]; then
-  cp "$INPUT_PDF" "$HOME/tmp/" || exit 1
+  export TMP_FILE="$HOME/tmp/$(basename $INPUT_PDF)"
+  cp "$INPUT_PDF" "$TMP_FILE" || exit 1
   echo "'$(basename $INPUT_PDF)' Has been copied to $HOME/tmp/"
   echo "Making Combined PDF..."
   echo " This Could Take a while!..."
-  pdftk A="$HOME/tmp/$(basename $INPUT_PDF)" B="$TEMPLATE_PDF" cat "A1-$PAGE" B1 "A$(($PAGE+1))-end" output "$HOME/tmp/output.pdf" || exit 1
-  export QUERY=''
-  read -p "Overwrite '$(basename $INPUT_PDF)' with new PDF? (y/N): " QUERY; export QUERY
-  if [ "$QUERY" == 'y' -o "$QUERY" == 'Y' ]; then
-    cp "$HOME/tmp/output.pdf" "$INPUT_PDF" || exit 1
-    echo SUCCESS!
-    exit 0
-  else 
-    read -p "New Output Filename (Same Directory as Input, omit .pdf suffix): " FILENAME; export FILENAME
-    if [ -e "$(dirname $INPUT_PDF)/$FILENAME.pdf" ]; then
-      echo "File '$FILENAME.pdf' Already Exists... Refusing to Overwrite..." >&2
-      echo "FAILED! Please retry with a different filename!" >&2
-      echo "The PDF is still here though, you can manually copy the it with:" >&2
-      echo "  cp ~/tmp/output.pdf ~/Books/$FILENAME--$(date +%F--%H-%M-%S).pdf" >&2
+  pdftk A="$HOME/tmp/$(basename $INPUT_PDF)" B="$TEMPLATE_PDF" cat "A1-$PAGE" B1 "A$(($PAGE+1))-end" output "$HOME/tmp/output.pdf"
+  PDFTK_ERR_CODE="$?"
+  if [ "$PDFTK_ERR_CODE" -ne 0 ]; then
+    echo "qpdf failed with error code: $PDFTK_ERR_CODE" >&2
+    echo "FAILED to Combine PDFs!" >&2
+    exit 1
+  fi
+  read -p "New Output Filename (Same Directory as Input, omit .pdf suffix): " FILENAME; export FILENAME
+  while [ -e "$(dirname $INPUT_PDF)/$FILENAME.pdf" ]; do
+    echo "File '$FILENAME.pdf' Already Exists... Refusing to Overwrite..." >&2
+    echo "FAILED! Please retry with a different filename!" >&2
+    echo ""
+    read -p "New Output Filename (Same Directory as Input, omit .pdf suffix) (OR Q to Quit): " FILENAME; export FILENAME
+    if [ "$FILENAME" == "Q" ]; then
+      echo "Quitting..." >&2
       exit 1
-    else
-      if [ ! -e "$(dirname $INPUT_PDF)/$FILENAME.pdf)" ]; then
-        export QUERY=''
-        read -p "Write New PDF: \'$(dirname $INPUT_PDF)/$FILENAME.pdf\'? (Y/n): " QUERY; export QUERY
-        if [ -z "$QUERY" -o "$QUERY" == "y" -o "$QUERY" == "Y" ]; then
-          if cp "$HOME/tmp/output.pdf" "$(dirname $INPUT_PDF)/$FILENAME.pdf"; then
-            echo "SUCCESS: Wrote Output to '$(dirname $INPUT_PDF)/$FILENAME.pdf'"
-            exit 0
-          else
-            echo "FAILED: Couldn't Write Output to '$(dirname $INPUT_PDF)/$FILENAME.pdf'" >&2
-            exit 1
-          fi
-        fi
-      else
-        echo "FAILED: Couldn't Write Output to '$(dirname $INPUT_PDF)/$FILENAME.pdf'" >&2
-        echo " FILE EXISTS!" >&2
-        exit 1
-      fi
     fi
+  done
+  if [ ! -e "$(dirname $INPUT_PDF)/$FILENAME.pdf)" ]; then
+    if cp "$HOME/tmp/output.pdf" "$(dirname $INPUT_PDF)/$FILENAME.pdf"; then
+      echo "SUCCESS: Wrote Output to '$(dirname $INPUT_PDF)/$FILENAME.pdf'"
+      exit 0
+    else
+      echo "FAILED: Couldn't Write Output to '$(dirname $INPUT_PDF)/$FILENAME.pdf'" >&2
+      exit 1
+    fi
+  else
+    echo "FAILED: Couldn't Write Output to '$(dirname $INPUT_PDF)/$FILENAME.pdf'" >&2
+    echo " FILE EXISTS!" >&2
+    exit 1
   fi
 else
   echo "Either '$INPUT_PDF' or '$TEMPLATE_PDF' Does Not Exist!" >&2
