Bug Fixes

diff --git a/pdf-ap b/pdf-ap
--- a/pdf-ap
+++ b/pdf-ap
@@ -67,20 +67,29 @@ if [ -f "$INPUT_PDF" -a -f "$TEMPLATE_PDF" ]; then
     exit 0
   else 
     read -p "New Output Filename (Same Directory as Input, omit .pdf suffix): " FILENAME; export FILENAME
-    if [ -e "$FILENAME.pdf" ]; then
+    if [ -e "$(dirname $INPUT_PDF)/$FILENAME.pdf" ]; then
       echo "File '$FILENAME.pdf' Already Exists... Refusing to Overwrite..." >&2
+      echo "FAILED! Please retry with a different filename!" >&2
+      echo "The PDF is still here though, you can manually copy the it with:" >&2
+      echo "  cp ~/tmp/output.pdf ~/Books/$FILENAME--$(date +%F--%H-%M-%S).pdf" >&2
       exit 1
     else
-      export QUERY=''
-      read -p "Write New PDF: '$(dirname $INPUT_PDF)/$FILENAME.pdf'? (y/N): " QUERY; export QUERY
-      if [ "$QUERY" == "y" -o "$QUERY" == "Y" ]; then
-        if cp "$HOME/tmp/output.pdf" "$(dirname $INPUT_PDF)/$FILENAME.pdf"; then
-          echo "SUCCESS: Wrote Output to '$(dirname $INPUT_PDF)/$FILENAME.pdf'"
-          exit 0
-        else
-          echo "FAILED: Couldn't Write Output to '$(dirname $INPUT_PDF)/$FILENAME.pdf'"
-          exit 1
+      if [ ! -e "$(dirname $INPUT_PDF/$FILENAME>pdf)" ]; then
+        export QUERY=''
+        read -p "Write New PDF: \'$(dirname $INPUT_PDF)/$FILENAME.pdf\'? (y/N): " QUERY; export QUERY
+        if [ "$QUERY" == "y" -o "$QUERY" == "Y" ]; then
+          if cp "$HOME/tmp/output.pdf" "$(dirname $INPUT_PDF)/$FILENAME.pdf"; then
+            echo "SUCCESS: Wrote Output to '$(dirname $INPUT_PDF)/$FILENAME.pdf'"
+            exit 0
+          else
+            echo "FAILED: Couldn't Write Output to '$(dirname $INPUT_PDF)/$FILENAME.pdf'" >&2
+            exit 1
+          fi
         fi
+      else
+        echo "FAILED: Couldn't Write Output to '$(dirname $INPUT_PDF)/$FILENAME.pdf'" >&2
+        echo " FILE EXISTS!" >&2
+        exit 1
       fi
     fi
   fi
